#ifndef __UNDEF_YAHSP_H__
#define __UNDEF_YAHSP_H__

// Definitions used in cpt-yahsp can break Boost or STL.
// FIXME These undef are inelegant, another solution should be used
// (eg : rename all cpt-yahsp definitions, or not use Boost, or...)

// The undef which are commented are the one mandatory to compile
// common parts between dae and cpt-yahsp.

#undef DO_PRAGMA
#undef OMP
#undef DO_PRAGMA
#undef OMP
#undef OMP_ATOMIC
#undef OMP_MASTER
#undef OMP_SINGLE
#undef OMP_CRITICAL
#undef OMP_BARRIER
#undef OMP_FLUSH
#undef OMP_PARALLEL
#undef state_create
#undef state_cmp
#undef state_clone
#undef state_copy
#undef state_contains
#undef state_add
#undef state_del
#undef set_atomic
#undef atomic
#undef set_constraint
#undef is_constraint
#undef function
#undef PLAN_FOUND
#undef GOALS_MUTEX
#undef INIT_PROP_FAILED
#undef BACKTRACK_LIMIT
#undef BOUND_LIMIT
#undef NO_PLAN
#undef TIMER
#undef start_timer
#undef get_timer
#undef get_wtimer
#undef choice_causal
#undef choice_action
#undef choice_action
#undef choice_action
#undef set_choice
#undef _inith
#undef _init_heuristic
#undef requires_min_level
#undef requires_max_level
#undef increases
#undef decreases
#undef assigns
#undef decrease
#undef increase
#undef assign
#undef causal_available
#undef print_trace
// #undef WORDSIZE
#undef BITS_VALUE
#undef BITS_TIME
#undef NOTRACE
#undef RESOURCES
#undef VALUEP
#undef MAXVAL
#undef VAL_UNKNOWN
#undef VALUEP
#undef MAXVAL
#undef VAL_UNKNOWN
#undef VALUEP
#undef MAXVAL
#undef VAL_UNKNOWN
#undef val_known
#undef val_unknown
#undef TIMEP
#undef MAXCOST
#undef time_round
#undef TIMEP
#undef MAXCOST
#undef time_round
#undef TIMEP
//#undef MAXTIME
#undef MAXCOST
#undef time_round
#undef STRING_MAX
// #undef NEST
#undef maxi
#undef mini
#undef maximize
#undef minimize
#undef exchange
//#undef check_alloc
#undef cpt_calloc
//#undef cpt_malloc
#undef cpt_realloc
//#undef cpt_free
// #undef VECTOR
// #undef EVECTOR
// #undef SVECTOR
// #undef _mkvector
#undef vector_copy
#undef vector_sort
/*
#undef bitarray_create
#undef bitarray_malloc
#undef bitarray_copy
#undef bitarray_clone
#undef bitarray_cmp
#undef bitarray_set_index
#undef bitarray_set
#undef bitarray_unset
#undef bitarray_get
#undef bitarray_save_and_set
*/
#undef _for
#undef _rfor
#undef FOR
#undef FORi
#undef FORMIN
#undef FORMINi
#undef FORMAX
#undef FORMAXi
#undef FORMINMAX
#undef RFOR
#undef RFORi
#undef RFORMIN
#undef RFORMINi
#undef RFORMAX
#undef RFORMAXi
#undef FOR
#undef FORPAIR
#undef FORCOUPLE
#undef EFOR
#undef EFORPAIR
#undef EFORCOUPLE
#undef cpt_srand
#undef cpt_rand
#undef LESS
#undef GREATER
#undef PREFER
#undef preferred
#undef mpz_get_timeval
#undef pddl_error
#undef increment_weight
#undef incr_weight
#undef linearval
#undef token_add
#undef get_areachable
#undef set_areachable
#undef get_reached_prec
#undef set_reached_prec
#undef inc_reached_prec
#undef get_freachable
#undef set_freachable
#undef YY_NO_INPUT
#undef YY_DECL
#undef propagate_event_queue
#undef propagate_all_queues
#undef keep_reachable_tab
#undef realdur
#undef REQ_NODE
#undef REQ_STEPS
#undef EXCH
#undef COMM
#undef NO_STATUS
#undef BYTE
#undef INT
#undef LONG
#undef LONG_INT
#undef DOUBLE
#undef ANY_SOURCE
#undef PACKED
#undef TR_normal
#undef TR_error
#undef TR_options
#undef TR_monitor
#undef TR_begin_bound
#undef TR_end_bound
#undef TR_restart
#undef TR_problem_stats
#undef TR_solution_plan
#undef TR_plan_stats
#undef TR_search_stats
#undef TR_yahsp_anytime_search_stats
#undef TR_new_world
#undef TR_backtrack
#undef TR_conflict_choice
#undef TR_support_choice
#undef TR_start_time_choice
#undef TR_mutex_choice
#undef TR_action_used
#undef TR_action_excluded
#undef TR_producer_used
#undef TR_rem_producer
#undef TR_order_before_aa
#undef TR_order_before_ca
#undef TR_order_before_ac
#undef TR_propagate_action
#undef TR_propagate_causal
#undef TR_synchronize_causal
#undef TR_protect_causal
#undef TR_protect_against
#undef TR_update_sup_a
#undef TR_update_inf_a
#undef TR_update_sup_c
#undef TR_update_inf_c
#undef TR_ratp
#undef TR_mpi
#undef begin_monitor
#undef end_monitor
#undef cpt_trace
#undef trace_proc
#undef begin_monitor
#undef end_monitor
#undef cpt_trace
#undef trace_proc
#undef ERR_allocation
#undef ERR_bucket
#undef ERR_no_plan
#undef ERR_user_interruption
#undef ERR_timer_interruption
#undef ERR_no_file
#undef ERR_parser
#undef ERR_max_plan_length
#undef ERR_options
#undef ERR_station
#undef error
#undef end_action
#undef CPT_PLAN_FOUND
#undef CPT_GOALS_MUTEX
#undef CPT_INIT_PROP_FAILED
#undef CPT_BACKTRACK_LIMIT
#undef CPT_BOUND_LIMIT
#undef CPT_NO_PLAN
#undef GLOBS_h
#undef check_allocation
#undef end_action
#undef CSIZE_ACTION
#undef CSIZE_CAUSAL
#undef FORPROD
#undef set_consumes
#undef unset_consumes
#undef consumes
#undef set_produces
#undef unset_produces
#undef produces
#undef set_deletes
#undef deletes
#undef set_edeletes
#undef edeletes
#undef set_amutex
#undef amutex
#undef set_fmutex
#undef unset_fmutex
//#undef fmutex
#undef set_precedes
#undef precedes
#undef set_distance
#undef distance
#undef store_distance
#undef distance_ca
#undef distance_ac
#undef set_deletes_included
#undef deletes_included
#undef duration
#undef first_start
#undef last_start
#undef first_end
#undef last_end
#undef delta_aa
#undef delta_ca
#undef delta_ac
#undef slack_aa
#undef slack_ca
#undef slack_ac
#undef cannot_precede_time_aa
#undef cannot_precede_aa
#undef cannot_precede_ca
#undef cannot_precede_ac
#undef can_precede_aa
#undef can_precede_ca
#undef can_precede_ac
#undef update_sup_a
#undef update_sup_c
#undef update_inf_a
#undef update_inf_c
#undef increment_inf_a
#undef decrement_sup_a
#undef producer
#undef value
#undef set_producer
#undef rem_producer
#undef can_produce
#undef is_produced
#undef get_producer
#undef get_nbprods
#undef activate_action
#undef activate_causal
#undef find_ac_constraint
#undef resource_local
#undef min_level
#undef max_level
#undef wdeg
#undef wdeg
#undef wdeg
#undef wdeg
#undef rdel
#undef dist
#undef min_distance
#undef min_distance
#undef mindist
#undef TEXT_WIDTH
#undef GETOPT
#undef GETOPT
#undef end_action
#undef get_ainit
#undef set_ainit
#undef get_finit
#undef set_finit
#undef get_areachable
#undef set_areachable
#undef set_pair_cost
#undef pair_cost
#undef clone_enum_variable
#undef clone_bound_variable
#undef STACK_INC
#undef nb_nodes
#undef nb_backtracks
#undef reset_backtracks
#undef current_world
#undef world_size
#undef set_backtrack_limit
#undef backtrack_limit
#undef backtrack_limit_reached
#undef nb_nodes_run
#undef nb_backtracks_run
#undef increase_propagations
#undef nb_propagations
#undef propagations_limit_reached
#undef set_limit_initprop
#undef limit_initprop
#undef alloc_stack
#undef push_stack
#undef pop_stack
#undef pop_var
#undef save
#undef store
#undef vstore
#undef new_world
#undef protected
#undef backtrack
#undef contradiction
#undef restore_initial_world
#undef EVENT_QUEUE_TYPE
#undef init_event_queues
#undef raz_event_queues
#undef init_queue
#undef register_var
#undef pop_event
#undef rem_event
#undef raz_queue
#undef post_event
#undef _init_queue
#undef _register_var
#undef _shift
#undef _pop_event
#undef _rem_event
#undef _raz_queue
#undef _post_event
#undef post_instantiate_event
#undef post_removal_event
#undef post_bound_event
#undef end_action
#undef get_ainit
#undef set_ainit
#undef get_aused
#undef set_aused
#undef get_finit
#undef set_finit
#undef COST
#undef INCCOST
#undef NODE_GVALUE
#undef NODE_HVALUE
#undef NODE_FVALUE
#undef support_threat
#undef mutex_threat
#undef DECLARE
#endif // __UNDEF_YAHSP_H__
