#!/bin/sh

here=$(pwd)

# cat install-dist.cmake | sed "s,<< PATH_TO_OPEN_MPI_STATIC >>,$here/openmpi," > install.cmake
cat dae/install-dist.cmake | sed "s,<<PATH_TO_PARADISEO>>,$here/paradiseo," > dae/install.cmake

echo "Build ParadisEO"
cd paradiseo
mkdir -p release
cd release/
cmake ..
make eo eoutils eoserial

echo "Build DAE"
cd $here/
mkdir -p release
# necessary library not installed on the DES
mkdir -p release/lib
cp libtermcap.a  release/lib/
cp libncurses.so release/lib/
cd release/
cmake -DBUILD_DAE_MO=off -DCMAKE_BUILD_TYPE=Release -DCPT_WITH_MPI=off -DCPT_WITH_OMP=off -DDAE_WITH_MPI=off -DDAE_WITH_OMP=off ..
make dae

cp ./dae/dae $here/dae_yahsp

