#!/bin/sh

here=`pwd`

echo "BUILD YAHSP"
cd $here/daeyahsp/cpt-yahsp
./build_gcc_linux_release

echo "BUILD EO"
cd $here/eo
./build_gcc_linux_release

echo "BUILD DAE"
cd $here/daeyahsp/dae
cat install-dist.cmake | sed "s,<<PATH_TO_EO>>,$here/eo," > install.tmp
cat install.tmp | sed "s,<<PATH_TO_CPT_YAHSP>>,$here/daeyahsp/cpt-yahsp," > install.cmake
./build_ipc.sh

echo "COPY THE BINARY"
cp ./ipc/dae $here/dae_yahsp

cd $here

