.TH "Main module" 3 "22 Jun 2006" "Version 1.4" "gdsl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Main module \- 
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBgdsl_get_version\fP (void)"
.br
.RI "\fIGet GDSL version number as a string. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* gdsl_get_version (void)"
.PP
Get GDSL version number as a string. 
.PP
\fBNote:\fP
.RS 4
Complexity: O( 1 ) 
.RE
.PP
\fBPrecondition:\fP
.RS 4
nothing. 
.RE
.PP
\fBPostcondition:\fP
.RS 4
the returned string MUST NOT be deallocated. 
.RE
.PP
\fBReturns:\fP
.RS 4
the GDSL version number as a string. 
.RE
.PP

